/**
 * AUTO-GENERATED FILE - DO NOT EDIT!
 *
 * This file was automatically generated by nestjs-trpc.
 * Any manual changes will be overwritten on the next generation.
 *
 * Command: `npx nestjs-trpc generate`
 * Learn more: https://nestjs-trpc.io
 */

import { initTRPC } from "@trpc/server";
import { z } from "zod";

const t = initTRPC.create();
const publicProcedure = t.procedure;
import type { GithubProfileRouter } from "../profile/profile.router";

const appRouter = t.router({
  githubProfileRouter: t.router({
    getGithubProfile: publicProcedure
      .input(z.object({
      username: z.string(),
    }))
      .query(async () => "PLACEHOLDER_DO_NOT_REMOVE" as unknown as Awaited<ReturnType<GithubProfileRouter["getGithubProfile"]>>)
    })
});

export type AppRouter = typeof appRouter;
